- name: vars preference
  hosts: local
  connection: local
  vars:
    NAME: "Keerthi from play"
    COURSE: "Ansible from play"
  # vars_files:
  # - vars.yaml
  # vars_prompt:
  # - name: NAME
  #   prompt: "Please enter the name"
  #   private: false
  tasks:
  - name: print name from tasks
    # vars:
    #   NAME: "Keerthi from tasks"
    ansible.builtin.debug: 
      msg: "Hi, I am {{ NAME }}"