- name: gathering facts
  hosts: local
  connection: local
  tasks: 
  - name: Print ansible facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: check os family is redhat
    ansible.builtin.debug:
      msg: "Yes, It's RedHat"
    when: ansible_facts.os_family == "RedHat"

  - name: check os family is debian
    ansible.builtin.debug:
      msg: "Yes, It's Debian"
    when: ansible_facts.os_family == "Debian"