- name: filters playbook
  hosts: local
  connection: local
  vars: 
    fruits: apple, banana, mango, grapes
    course: "Ansible"
    myIp: "172.31.67.105"
    tags:
      Name: ansible
      project: roboshop
      component: catalogue

  tasks: 
  - name: print greeting
    ansible.builtin.debug:
      msg: "Hi Keerthi, {{ GREETING | default('Good Morning') }}"

  - name: Convert string to list
    ansible.builtin.debug:
      msg: "{{ fruits | split(',') }}"

  - name: Convert dictionary to items
    ansible.builtin.debug:
      msg: "{{ tags | dict2items  }}"

  - name: convert to upper case
    ansible.builtin.debug:
      msg: "{{ course | upper }}"

  - name: convert to lower case
    ansible.builtin.debug:
      msg: "{{ course | lower }}"

  - name: check ipv4
    ansible.builtin.debug:
      msg: "{{ myIp | ansible.utils.ipv4 }}"